2020-09-05 12:52:20,083 (16374/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-05 12:52:20,084 (16374/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-09-05 12:52:25,195 (16374/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 558, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "nikhil_shrv"\n\n'
2020-09-05 12:52:28,165 (16427/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-05 12:52:28,165 (16427/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-09-05 12:52:30,107 (16427/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 558, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "nikhil_shrv"\n\n'
2020-09-05 12:52:32,062 (16449/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-05 12:52:32,062 (16449/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-09-05 12:52:34,257 (16449/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 558, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "nikhil_shrv"\n\n'
2020-09-05 12:54:10,567 (16775/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-05 12:54:10,569 (16775/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-09-05 12:54:24,008 (16775/MainThread) pgcli.pgexecute ERROR - sql: 'selec', error: SyntaxError('syntax error at or near "selec"\nLINE 1: selec\n        ^\n')
2020-09-05 12:54:24,016 (16775/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "selec"\nLINE 1: selec\n        ^\n\n'
2020-09-07 09:53:42,260 (15582/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-07 09:53:42,261 (15582/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-09-07 10:13:16,831 (15582/MainThread) pgcli.pgexecute ERROR - sql: "select * from outreachcircle.outreach_circle where name = 'Melissa Baten Caswell for SCCBOE'", error: OperationalError('SSL SYSCALL error: Operation timed out\n')
2020-09-07 10:13:16,875 (15582/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: SSL SYSCALL error: Operation timed out\n\n'
2020-09-07 10:13:16,875 (15582/MainThread) pgcli.main ERROR - sql: "select * from outreachcircle.outreach_circle where name = 'Melissa Baten Caswell for SCCBOE';", error: OperationalError('SSL SYSCALL error: Operation timed out\n')
2020-09-07 10:13:16,894 (15582/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: SSL SYSCALL error: Operation timed out\n\n'
2020-10-03 19:40:28,156 (92611/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-03 19:40:28,157 (92611/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-10-03 19:41:10,048 (92611/MainThread) pgcli.pgexecute ERROR - sql: 'select * from outreachcircle.audience where idoc', error: UndefinedColumn('column "idoc" does not exist\nLINE 1: select * from outreachcircle.audience where idoc\n                                                    ^\nHINT:  Perhaps you meant to reference the column "audience.id".\n')
2020-10-03 19:41:10,049 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "idoc" does not exist\nLINE 1: select * from outreachcircle.audience where idoc\n                                                    ^\nHINT:  Perhaps you meant to reference the column "audience.id".\n\n'
2020-10-03 19:41:49,517 (92611/MainThread) pgcli.pgexecute ERROR - sql: 'update outreachcircle.au', error: SyntaxError('syntax error at end of input\nLINE 1: update outreachcircle.au\n                                ^\n')
2020-10-03 19:41:49,523 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: update outreachcircle.au\n                                ^\n\n'
2020-10-03 19:42:14,225 (92611/MainThread) pgcli.pgexecute ERROR - sql: "update outreachcircle.audience set id = '87d16a47-e043-4e22-8d77-159392cc42bb' where id_outreach_circle = 'e3d30ea4-a1f1-4389-984f-8abc596b5f77'", error: UniqueViolation('duplicate key value violates unique constraint "audience_pk"\nDETAIL:  Key (id)=(87d16a47-e043-4e22-8d77-159392cc42bb) already exists.\n')
2020-10-03 19:42:14,225 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "audience_pk"\nDETAIL:  Key (id)=(87d16a47-e043-4e22-8d77-159392cc42bb) already exists.\n\n'
2020-10-03 19:45:07,596 (92611/MainThread) pgcli.pgexecute ERROR - sql: "select * from outreachcircle.audience_action where id_audience = 'eb4a3a31-551f-4065-9f73-026a6fc18f9'", error: InvalidTextRepresentation('invalid input syntax for uuid: "eb4a3a31-551f-4065-9f73-026a6fc18f9"\nLINE 1: ...utreachcircle.audience_action where id_audience = \'eb4a3a31-...\n                                                             ^\n')
2020-10-03 19:45:07,596 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTextRepresentation: invalid input syntax for uuid: "eb4a3a31-551f-4065-9f73-026a6fc18f9"\nLINE 1: ...utreachcircle.audience_action where id_audience = \'eb4a3a31-...\n                                                             ^\n\n'
2020-10-03 19:45:11,192 (92611/MainThread) pgcli.pgexecute ERROR - sql: "select * from outreachcircle.audience_action where id_audience = 'eb4a3a31-551f-4065-9f73-026a6fc18f9'", error: InvalidTextRepresentation('invalid input syntax for uuid: "eb4a3a31-551f-4065-9f73-026a6fc18f9"\nLINE 1: ...utreachcircle.audience_action where id_audience = \'eb4a3a31-...\n                                                             ^\n')
2020-10-03 19:45:11,193 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTextRepresentation: invalid input syntax for uuid: "eb4a3a31-551f-4065-9f73-026a6fc18f9"\nLINE 1: ...utreachcircle.audience_action where id_audience = \'eb4a3a31-...\n                                                             ^\n\n'
2020-10-03 19:45:26,355 (92611/MainThread) pgcli.pgexecute ERROR - sql: 'select * from outreachcircle.mapping', error: UndefinedTable('relation "outreachcircle.mapping" does not exist\nLINE 1: select * from outreachcircle.mapping\n                      ^\n')
2020-10-03 19:45:26,361 (92611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "outreachcircle.mapping" does not exist\nLINE 1: select * from outreachcircle.mapping\n                      ^\n\n'
2020-10-03 19:53:34,918 (95856/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-03 19:53:34,919 (95856/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
